# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night:
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: ''
    description: '面向ZDEM用户的官方网站'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: '3b4b7fe5371618b984124ff194544bed'
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: true
    show_day_night: false
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  block: minimal
  copyright:
    notice: '© 2017 – {year} ZDEM官网.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false
  # For multilingual sites, show a language chooser in the footer?
  show_translations: true
  
# Localization

locale:
  date_format: '2006年01月02日'
  time_format: '15:04'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - bash
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/geovbox/geovbox.com'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: master
    local_backend: false
  academicons:
    enable: true

