#language: python
#python: 3.6
language: generic

install:
  - curl -L https://raw.githubusercontent.com/geovbox/geovbox.com/master/install-hugo.sh | bash

script:
  - ./hugo 

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  local_dir: public
