baseURL = "https://geovbox.com/"
#/home/lichangsheng/desktop/vbox1.3/doc/geovbox.com/public
languageCode = "zh-cmn-Hans"
title = "构造模拟实验室"
defaultContentLanguage = "zh-cn" # en / zh-CN / ... (This field determines which i18n file to use)
defaultContentLanguageInSubdir= false

paginate = 10
disablePathToLower = true
preserveTaxonomyNames = true
hasCJKLanguage = true
defaultLayout = "news"
ignoreFiles = ["vbox-users.dat",
               "GeoJSON.pl",
               "gmt.history",
               "gmt.conf",
               "\\.ps$",
              ]
rssLimit = 20
resourceDir = ".resources"

[blackfriday]
    hrefTargetBlank = true

[taxonomies]
    tag = "tags"
    category = "categories"
    author = "authors"

[permalinks]
    blog = "/blog/:slug/"

[author]
    name = "[苏ICP备：17006658号](http://www.beian.miit.gov.cn)"
    email = "geovbox@163.com"

[params]
    description = "面向 构造数值模拟 用户"
    copyright = "Powered by [Hugo](https://gohugo.io) & Hosted by [GitHub](https://github.com/geovbox/geovbox.com)."
    
    # Format dates with Go's time formating
    since = 2017
    date_format = "2006年01月02日"

    sectionsInGallery = ["example","blog","am"]

    userMap = "vbox-users.json"


[Languages]
[Languages.zh-cn]
title = "StructLab"
weight = 0
languageName = "中文"

[Languages.zh-cn.params]
    date_format = "2006年01月02日"
# Navigation Links
#   The weight parameter defines the order that the links will appear in.
[[Languages.zh-cn.menu.main]]
    name = "首页"
    url = "/"
    weight = 1

[[Languages.zh-cn.menu.main]]
    name = "手册"
    url = "https://doc.geovbox.com"
    weight = 2
    
[[Languages.zh-cn.menu.main]]
    name = "视频教程"
    url = "/video/"
    weight = 3
    
[[Languages.zh-cn.menu.main]]
    name = "图库"
    url = "/gallery/"
    weight = 4

[[Languages.zh-cn.menu.main]]
    name = "示例"
    url = "/example/"
    weight = 5

[[Languages.zh-cn.menu.main]]
    name = "新闻案例"
    url = "/blog/"
    weight = 6

[[Languages.zh-cn.menu.main]]
    name = "物理模拟"
    url = "/am/"
    weight = 7
#[[Languages.zh-cn.menu.main]]
#    name = "计算平台"
#    url = "/hpc/"
#    weight = 8
[[Languages.zh-cn.menu.main]]
    name = "软件"
    url = "/download/"
    weight = 9
[[Languages.zh-cn.menu.main]]
    name = "论文"
    url = "/paper/"
    weight = 10
[[Languages.zh-cn.menu.main]]
    name = "关于"
    url = "/about/"
    weight = 11

#[[Languages.zh-cn.menu.icon]]
#    name = "qq"
#    url = "/images/qq-group.png"
#    weight = 11

#[[Languages.zh-cn.menu.icon]]
#    name = "github"
#    url = "https://github.com/geovbox"
#    weight = 12

#[[Languages.zh-cn.menu.icon]]
#    name = "envelope"
#    url = "mailto:geovbox@163.com"
#    weight = 13


[Languages.en]
weight = 20
languageName = "English"
title = "VBOX"

[Languages.en.params]
    date_format = "2 Jan 2006"
[Languages.en.author]
    name = "VBOX"
# Navigation Links
#   The weight parameter defines the order that the links will appear in.
[[Languages.en.menu.main]]
    name = "Home"
    url = "/en/"
    weight = 21

[[Languages.en.menu.main]]
    name = "Doc"
    url = "https://doc.geovbox.com"
    weight = 22
    
[[Languages.en.menu.main]]
    name = "Video"
    url = "/video/"
    weight = 23
    
[[Languages.en.menu.main]]
    name = "Gallery"
    url = "/en/gallery/"
    weight = 24

[[Languages.en.menu.main]]
    name = "Example"
    url = "/en/example/"
    weight = 25

[[Languages.en.menu.main]]
    name = "News"
    url = "/en/blog/"
    weight = 26

[[Languages.en.menu.main]]
    name = "Analog Model"
    url = "/en/am/"
    weight = 27

#[[Languages.en.menu.main]]
#    name = "HPC"
#    url = "/en/hpc/"
#    weight = 28
    
[[Languages.en.menu.main]]
    name = "Download"
    url = "/en/download/"
    weight = 29

[[Languages.en.menu.main]]
    name = "Paper"
    url = "/en/paper/"
    weight = 30

[[Languages.en.menu.main]]
    name = "About"
    url = "/en/about/"
    weight = 31

#[[Languages.en.menu.icon]]
#    name = "qq"
#    url = "/images/qq-group.png"
#    weight = 32

#[[Languages.en.menu.icon]]
#    name = "github"
#    url = "https://github.com/geovbox"
#    weight = 33

#[[Languages.en.menu.icon]]
#    name = "envelope"
#    url = "mailto:geovbox@163.com"
#    weight = 34
